"""init migr

Revision ID: 14eeaac6f402
Revises: 
Create Date: 2025-05-26 22:13:08.918987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14eeaac6f402'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_forecast_city'), table_name='forecast')
    op.drop_index(op.f('ix_forecast_id'), table_name='forecast')
    op.drop_table('forecast')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forecast',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('city', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forecast_id'), 'forecast', ['id'], unique=False)
    op.create_index(op.f('ix_forecast_city'), 'forecast', ['city'], unique=False)
    # ### end Alembic commands ###
